=== Bayons/TDS/UsuariosUnix.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT sistema (usuario, grupo)*>
<!ELEMENT usuario (nombre, password, home, nombreCompleto?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT home (#PCDATA)>
<!ELEMENT nombreCompleto (#PCDATA)>

<!ATTLIST usuario uId ID #REQUIRED
        shell (bash | ash | csh | Zsh | ksh | tcsh) "bash"
        grupoPrincipal IDREF #REQUIRED
        grupoSecundarios IDREFS #IMPLIED
        >

<!ELEMENT grupo EMPTY >

<!ATTLIST grupo nombre CDATA #REQUIRED
        gId ID #REQUIRED
        miembros IDREFS #IMPLIED>

=== Bayons/TDS/UsuariosUnix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistema SYSTEM "UsuariosUnix.dtd" >
<sistema>
  <usuario grupoPrincipal="GRUPONUEVO 1" grupoSecundarios="null" shell="bash" uId="8">
    <nombre>Bayons</nombre>
    <password>secreto</password>
    <home>home</home>
    <nombreCompleto>MiguelBayonSanz</nombreCompleto>
  </usuario>
<usuario grupoPrincipal="NUEVOGRUPO 2" grupoSecundarios="jamonSerraner" shell="bash" uId="9">
    <nombre>Antits</nombre>
    <password>contrasena</password>
    <home>home</home>
    <nombreCompleto>GuillermoAnta</nombreCompleto>
  </usuario>
  <grupo gId="1" miembros="2" nombre="GRUPONUEVO 1"/>
  <grupo gId="2" miembros="4" nombre="NUEVOGRUPO 2"/>
    
</sistema>
